spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/webpos?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
zuul:
  sensitive-headers:
  routes:
    token:
      url: http://localhost:9002
    order:
      url: http://localhost:9003
  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
      - limit: 1
        quota: 1
        refresh-interval: 1
        type:
          - url
          - httpmethod
server:
  port: 9001