spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/webpos?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9080